default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: webxx_development

test:
  <<: *default
  database: webxx_test

production:
  <<: *default
  database: webxx_production
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || '5432' %>